; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgpu9.42-amd-amdhsa -verify-machineinstrs < %s | FileCheck --check-prefix=GFX942 %s
; RUN: llc -mtriple=amdgpu9.42-amd-amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck --check-prefix=GFX942 %s
; RUN: llc -mtriple=amdgpu9.50-amd-amdhsa -verify-machineinstrs < %s | FileCheck --check-prefix=GFX950 %s
; RUN: llc -mtriple=amdgpu9.42-amd-amdhsa -structurizecfg-skip-uniform-regions -verify-machineinstrs < %s | FileCheck --check-prefix=PAD %s
; RUN: not llc -mtriple=amdgpu9.0a-amd-amdhsa -filetype=null < %s 2>&1 | FileCheck --check-prefix=GFX90A-ERR %s

; GFX90A-ERR: llvm.amdgcn.buffer.inv requires target feature 'gfx940-insts'

declare void @llvm.amdgcn.buffer.inv(i32 immarg)
declare i32 @llvm.amdgcn.workitem.id.x()

define amdgpu_kernel void @buffer_inv_cache_policies() {
; GFX942-LABEL: buffer_inv_cache_policies:
; GFX942:       ; %bb.0:
; GFX942-NEXT:    buffer_inv
; GFX942-NEXT:    buffer_inv sc0
; GFX942-NEXT:    buffer_inv sc1
; GFX942-NEXT:    buffer_inv sc0 sc1
; GFX950-LABEL: buffer_inv_cache_policies:
; GFX950:       ; %bb.0:
; GFX950-NEXT:    buffer_inv
; GFX950-NEXT:    buffer_inv sc0
; GFX950-NEXT:    buffer_inv sc1
; GFX950-NEXT:    buffer_inv sc0 sc1
  call void @llvm.amdgcn.buffer.inv(i32 0)
  call void @llvm.amdgcn.buffer.inv(i32 1)
  call void @llvm.amdgcn.buffer.inv(i32 16)
  call void @llvm.amdgcn.buffer.inv(i32 17)
  ret void
}

; This is the unpadded baseline for explicit VM_CNT padding. Without the
; intrinsic on the short path, the common load must be fully waited on at the
; join.
define amdgpu_kernel void @short_path_unpadded(ptr addrspace(1) %in,
                                               ptr addrspace(1) %out,
                                               i32 inreg %take.long.path) {
; PAD-LABEL: short_path_unpadded:
; PAD:       global_load_dword
; PAD-NOT:   buffer_inv
; PAD:       ; %join
; PAD:       s_waitcnt vmcnt(0)
; PAD-NEXT:  v_add_u32
entry:
  %id = call i32 @llvm.amdgcn.workitem.id.x()
  %idx = zext i32 %id to i64
  %addr = getelementptr i32, ptr addrspace(1) %in, i64 %idx
  %common = load i32, ptr addrspace(1) %addr, align 4
  %take.long = icmp ne i32 %take.long.path, 0
  br i1 %take.long, label %long, label %short,
     !structurizecfg.uniform !0, !amdgpu.uniform !0

long:
  %next.idx = add i64 %idx, 1
  %next = getelementptr i32, ptr addrspace(1) %in, i64 %next.idx
  %extra = load volatile i32, ptr addrspace(1) %next, align 4
  br label %join, !structurizecfg.uniform !0

short:
  br label %join, !structurizecfg.uniform !0

join:
  %common.plus = add i32 %common, 1
  store i32 %common.plus, ptr addrspace(1) %out, align 4
  ret void
}

; A buffer_inv with no cache policy flags increments VM_CNT without
; invalidating a cache. Placing it on the short path equalizes the paths and
; allows the common load's wait to leave one later event outstanding.
define amdgpu_kernel void @short_path_padded(ptr addrspace(1) %in,
                                             ptr addrspace(1) %out,
                                             i32 inreg %take.long.path) {
; PAD-LABEL: short_path_padded:
; PAD:       global_load_dword
; PAD:       buffer_inv
; PAD:       ; %join
; PAD:       s_waitcnt vmcnt(1)
; PAD-NEXT:  v_add_u32
entry:
  %id = call i32 @llvm.amdgcn.workitem.id.x()
  %idx = zext i32 %id to i64
  %addr = getelementptr i32, ptr addrspace(1) %in, i64 %idx
  %common = load i32, ptr addrspace(1) %addr, align 4
  %take.long = icmp ne i32 %take.long.path, 0
  br i1 %take.long, label %long, label %short,
     !structurizecfg.uniform !0, !amdgpu.uniform !0

long:
  %next.idx = add i64 %idx, 1
  %next = getelementptr i32, ptr addrspace(1) %in, i64 %next.idx
  %extra = load volatile i32, ptr addrspace(1) %next, align 4
  br label %join, !structurizecfg.uniform !0

short:
  call void @llvm.amdgcn.buffer.inv(i32 0)
  br label %join, !structurizecfg.uniform !0

join:
  %common.plus = add i32 %common, 1
  store i32 %common.plus, ptr addrspace(1) %out, align 4
  ret void
}

!0 = !{}
